/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    flatDir {
        dirs("libs/")
    }
}

dependencies {
    implementation("junit:junit:4.13.2")
    implementation("org.apache.httpcomponents.client5:httpclient5:5.1.3")
    implementation("com.google.code.gson:gson:2.9.0")
    implementation(files("libs/kodenoobsjudge-0.1.0.jar"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.kodenoobs.hiring.Task1SubmissionRunner")
}
